/* 
 * DealersAndVehicles
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ClientApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class ClientApiTests
    {
        private ClientApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new ClientApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ClientApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' ClientApi
            //Assert.IsInstanceOfType(typeof(ClientApi), instance, "instance is a ClientApi");
        }

        
        /// <summary>
        /// Test Generate
        /// </summary>
        [Test]
        public void GenerateTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string language = null;
            //instance.Generate(language);
            
        }
        
        /// <summary>
        /// Test Index
        /// </summary>
        [Test]
        public void IndexTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //instance.Index();
            
        }
        
    }

}
