/* 
 * DealersAndVehicles
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing DataSetApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class DataSetApiTests
    {
        private DataSetApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new DataSetApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DataSetApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' DataSetApi
            //Assert.IsInstanceOfType(typeof(DataSetApi), instance, "instance is a DataSetApi");
        }

        
        /// <summary>
        /// Test GetCheat
        /// </summary>
        [Test]
        public void GetCheatTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string datasetId = null;
            //var response = instance.GetCheat(datasetId);
            //Assert.IsInstanceOf<Answer> (response, "response is Answer");
        }
        
        /// <summary>
        /// Test GetDataSetId
        /// </summary>
        [Test]
        public void GetDataSetIdTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.GetDataSetId();
            //Assert.IsInstanceOf<DatasetIdResponse> (response, "response is DatasetIdResponse");
        }
        
        /// <summary>
        /// Test PostAnswer
        /// </summary>
        [Test]
        public void PostAnswerTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string datasetId = null;
            //Answer answer = null;
            //var response = instance.PostAnswer(datasetId, answer);
            //Assert.IsInstanceOf<AnswerResponse> (response, "response is AnswerResponse");
        }
        
    }

}
