/* 
 * DealersAndVehicles
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing VehiclesApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class VehiclesApiTests
    {
        private VehiclesApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new VehiclesApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of VehiclesApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' VehiclesApi
            //Assert.IsInstanceOfType(typeof(VehiclesApi), instance, "instance is a VehiclesApi");
        }

        
        /// <summary>
        /// Test GetIds
        /// </summary>
        [Test]
        public void GetIdsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string datasetId = null;
            //var response = instance.GetIds(datasetId);
            //Assert.IsInstanceOf<VehicleIdsResponse> (response, "response is VehicleIdsResponse");
        }
        
        /// <summary>
        /// Test GetVehicle
        /// </summary>
        [Test]
        public void GetVehicleTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string datasetId = null;
            //int? vehicleid = null;
            //var response = instance.GetVehicle(datasetId, vehicleid);
            //Assert.IsInstanceOf<VehicleResponse> (response, "response is VehicleResponse");
        }
        
    }

}
