/* 
 * DealersAndVehicles
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// DealerAnswer
    /// </summary>
    [DataContract]
    public partial class DealerAnswer :  IEquatable<DealerAnswer>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DealerAnswer" /> class.
        /// </summary>
        /// <param name="dealerId">dealerId.</param>
        /// <param name="name">name.</param>
        /// <param name="vehicles">vehicles.</param>
        public DealerAnswer(int? dealerId = default(int?), string name = default(string), List<VehicleAnswer> vehicles = default(List<VehicleAnswer>))
        {
            this.DealerId = dealerId;
            this.Name = name;
            this.Vehicles = vehicles;
        }
        
        /// <summary>
        /// Gets or Sets DealerId
        /// </summary>
        [DataMember(Name="dealerId", EmitDefaultValue=false)]
        public int? DealerId { get; set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [DataMember(Name="name", EmitDefaultValue=false)]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets Vehicles
        /// </summary>
        [DataMember(Name="vehicles", EmitDefaultValue=false)]
        public List<VehicleAnswer> Vehicles { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class DealerAnswer {\n");
            sb.Append("  DealerId: ").Append(DealerId).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Vehicles: ").Append(Vehicles).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as DealerAnswer);
        }

        /// <summary>
        /// Returns true if DealerAnswer instances are equal
        /// </summary>
        /// <param name="input">Instance of DealerAnswer to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(DealerAnswer input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.DealerId == input.DealerId ||
                    (this.DealerId != null &&
                    this.DealerId.Equals(input.DealerId))
                ) && 
                (
                    this.Name == input.Name ||
                    (this.Name != null &&
                    this.Name.Equals(input.Name))
                ) && 
                (
                    this.Vehicles == input.Vehicles ||
                    this.Vehicles != null &&
                    this.Vehicles.SequenceEqual(input.Vehicles)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.DealerId != null)
                    hashCode = hashCode * 59 + this.DealerId.GetHashCode();
                if (this.Name != null)
                    hashCode = hashCode * 59 + this.Name.GetHashCode();
                if (this.Vehicles != null)
                    hashCode = hashCode * 59 + this.Vehicles.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
