/* 
 * DealersAndVehicles
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// VehicleIdsResponse
    /// </summary>
    [DataContract]
    public partial class VehicleIdsResponse :  IEquatable<VehicleIdsResponse>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="VehicleIdsResponse" /> class.
        /// </summary>
        /// <param name="vehicleIds">vehicleIds.</param>
        public VehicleIdsResponse(List<int?> vehicleIds = default(List<int?>))
        {
            this.VehicleIds = vehicleIds;
        }
        
        /// <summary>
        /// Gets or Sets VehicleIds
        /// </summary>
        [DataMember(Name="vehicleIds", EmitDefaultValue=false)]
        public List<int?> VehicleIds { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class VehicleIdsResponse {\n");
            sb.Append("  VehicleIds: ").Append(VehicleIds).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as VehicleIdsResponse);
        }

        /// <summary>
        /// Returns true if VehicleIdsResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of VehicleIdsResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(VehicleIdsResponse input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.VehicleIds == input.VehicleIds ||
                    this.VehicleIds != null &&
                    this.VehicleIds.SequenceEqual(input.VehicleIds)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.VehicleIds != null)
                    hashCode = hashCode * 59 + this.VehicleIds.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
