/* 
 * DealersAndVehicles
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing DatasetIdResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class DatasetIdResponseTests
    {
        // TODO uncomment below to declare an instance variable for DatasetIdResponse
        //private DatasetIdResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DatasetIdResponse
            //instance = new DatasetIdResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DatasetIdResponse
        /// </summary>
        [Test]
        public void DatasetIdResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" DatasetIdResponse
            //Assert.IsInstanceOfType<DatasetIdResponse> (instance, "variable 'instance' is a DatasetIdResponse");
        }


        /// <summary>
        /// Test the property 'DatasetId'
        /// </summary>
        [Test]
        public void DatasetIdTest()
        {
            // TODO unit test for the property 'DatasetId'
        }

    }

}
