/* 
 * DealersAndVehicles
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing VehicleAnswer
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class VehicleAnswerTests
    {
        // TODO uncomment below to declare an instance variable for VehicleAnswer
        //private VehicleAnswer instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of VehicleAnswer
            //instance = new VehicleAnswer();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of VehicleAnswer
        /// </summary>
        [Test]
        public void VehicleAnswerInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" VehicleAnswer
            //Assert.IsInstanceOfType<VehicleAnswer> (instance, "variable 'instance' is a VehicleAnswer");
        }


        /// <summary>
        /// Test the property 'VehicleId'
        /// </summary>
        [Test]
        public void VehicleIdTest()
        {
            // TODO unit test for the property 'VehicleId'
        }
        /// <summary>
        /// Test the property 'Year'
        /// </summary>
        [Test]
        public void YearTest()
        {
            // TODO unit test for the property 'Year'
        }
        /// <summary>
        /// Test the property 'Make'
        /// </summary>
        [Test]
        public void MakeTest()
        {
            // TODO unit test for the property 'Make'
        }
        /// <summary>
        /// Test the property 'Model'
        /// </summary>
        [Test]
        public void ModelTest()
        {
            // TODO unit test for the property 'Model'
        }

    }

}
