/* 
 * DealersAndVehicles
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing VehicleIdsResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class VehicleIdsResponseTests
    {
        // TODO uncomment below to declare an instance variable for VehicleIdsResponse
        //private VehicleIdsResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of VehicleIdsResponse
            //instance = new VehicleIdsResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of VehicleIdsResponse
        /// </summary>
        [Test]
        public void VehicleIdsResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" VehicleIdsResponse
            //Assert.IsInstanceOfType<VehicleIdsResponse> (instance, "variable 'instance' is a VehicleIdsResponse");
        }


        /// <summary>
        /// Test the property 'VehicleIds'
        /// </summary>
        [Test]
        public void VehicleIdsTest()
        {
            // TODO unit test for the property 'VehicleIds'
        }

    }

}
